### ISSUE TITLE
[Masks]: Allow query strings to be masked

### ISSUE THREAD

**Issue by tolgap** [jmcdo29/ogma#1266]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

OAuth usually passes things like `hmac` and `code` as query params. These get logged as is, as the `HttpInterceptorService.getCallPoint()` does nothing but return `request.originalUrl`.

### Describe the solution you'd like

I would like to apply masks to query strings as well.

### What is the motivation / use case for changing the behavior?

Increase security when logging HTTP requests.

**Comment by jmcdo29** [comment]
Hmm, I could see why wanting to mask these would be nice. I'll think about if this could be brought into a config in any way, but right now the request parsers don't take in any config objects.

What can be done at the moment is extend the existing `ExpressParser` (or whatever HTTP engine you're using) and add in this masking yourself.
```ts
@Injectbale()
export class ExpressOauthMaskingParser extends ExpressParser {
  getCallPoint(context: ExecutionContext) {
    const url = super.getCallPoint(context);
    if (url.includes('callback')) { // assumption of an OAuth callback URL
      const parts = url.split('/');
      const maskVal = parts.pop();
      return parts.join('/') + '/' + maskVal.replaceAll(/./g, '*')
  }
  return url
}
```

Now, this explicitly masks the entire return in the last position of the URL (whatever is after the last `/`), but you could implement some query string parsing logic if you want to only mask certain values

**Comment by jmcdo29** [comment]
I think adding in an option for how to do this would bring in too much complexity in terms of maintenance for the library. That said, this is why the parsers are made as classes so that you are able to extend them to fit your exact use case. If you think of an easy way to integrate this I'll be happy to open it back up for discussion, but right now I think I'm going to keep the options as is and allow for the customization via class extension
