### ISSUE TITLE
[Parser]: Request ID

### ISSUE THREAD

**Issue by Ponjimon** [jmcdo29/ogma#52]
## Describe the solution you'd like

It would be nice if I could have an interceptor that adds some ID to requests (see example below) and than uses that ID in the log.

## What is the motivation / use case for changing the behavior?

Tracing. That way, if a user reports an issue they can also check the request ID that they got back from the server and then a developer can search that request ID inside the logs to easily track the request that was broken.

Example interceptor for adding request IDs:

```ts
import { Request, Response } from 'express';
import { v4 as uuidv4 } from 'uuid';

import { REQUEST_ID_TOKEN_HEADER } from '../constants';

export function RequestIdMiddleware(
  request: Request,
  response: Response,
  next: Function
): void {
  if (!request.headers[REQUEST_ID_TOKEN_HEADER]) {
    request.headers[REQUEST_ID_TOKEN_HEADER] = uuidv4();
  }
  response.set(
    REQUEST_ID_TOKEN_HEADER,
    request.headers[REQUEST_ID_TOKEN_HEADER]
  );

  next();
}
```

**Comment by jmcdo29** [comment]
This is something I've though about a lot and not sure which direction I want to take it. On the one hand, request tracing can be very useful for getting a full view of the request, but on the other, it can lead to some inconsistencies depending on how the user expects things to be managed. 

What may happen is have a middleware as suggested to set a tracing value in the header of the request and response as an opt-in kind of feature, but the problem I see with it is making it work for all Nest contexts and not just HTTP. 

Lastly, as for using the ID in the log, that would be left up to the developer (except for the interceptor which does request logging already), due to the fact that that would require the logger to become request scoped, and that is not in the spirit of **this** logger. 

I'll keep thinking about what can be done with the tracing ID and how it can work with the same contexts the logger already does

**Comment by nllahat** [comment]
hi @Ponjimon 
here's my implementation for the correlationId issue, until @jmcdo29 will come up with a better solution...

I added my own interceptor that adds a correlationId to each request:

```
@Injectable()
export class CorrelationIdInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    const ctx = context.switchToHttp();
    const response: Response = ctx.getResponse<Response>();
    const request: ExtendedRequest = ctx.getRequest();
    const correlationId = uuidv4();

    request.correlationId = correlationId;

    return next
      .handle()
      .pipe(
        tap(
          () => (response.set('x-correlation-id', correlationId)),
        ),
      );
  }
}
```

then I extended the ExpressParser to log the correlationId too (kind of a hack)

```
@Injectable()
export class CustomExpressParser extends ExpressParser {
  getMethod(context: ExecutionContext): string {
    const req = this.getRequest(context);
    const method = req.method || 'GET';

    return `${method} ${req.correlationId || 'NO-CORRELATION-ID'}`;
  }
}
```

Here's my OgmaModuleConfig:

```
@Injectable()
export class OgmaModuleConfig
  implements ModuleConfigFactory<OgmaModuleOptions> {
  constructor(private readonly configService: MyConfigService) {}

  createModuleConfig(): OgmaModuleOptions {
    return {
      service: {
        logLevel: this.configService.getLogLevel(),
        color: true,
        application: this.configService.getAppName(),
      },
      interceptor: {
        http: CustomExpressParser,
      },
    };
  }
}
```

and now each express log will contain the correlation id.

hope it was helpful..
