### ISSUE TITLE
Wrong return code when using an exception filter

### ISSUE THREAD

**Issue by crebier-corentin** [jmcdo29/ogma#6]
Reproduction repository: https://github.com/bibo5088/nest-ogma-bug

The browser correctly shows a 400 code, while ogma logs a 500 code.

**Comment by jmcdo29** [comment]
So, the issue here is that filters run after interceptors do, so throwing an error lets the interceptor catch it, say "This is not a Nest Exception, so it's an error code 500" and throw the error to let any other error handling happen. Unfortunately, with the way that filters work, there's no easy way to let a filter catch an error, log it, and pass it to the next filter, unless there is a class structure being used. As the idea of the module is to have most of this as automatic as possible, there isn't a good solution when it comes to dealing with errors and filters.

## Options

* Leave the functionality as is, and have the `OgmaIntercetpor` _attempt_ to guess the error code
* Create an `OgmaFilter` that other filters can extend and leave it up to the dev to call `super.catch()` which would only log the error and be a `void` function
* Something else I'm currently not thinking of (open to other ideas)

What do you think?

**Comment by crebier-corentin** [comment]
None of these solution seems ideal, this is more of an issue with the framework.
I guess the best solution for me is to extend HttpException for my exceptions.

**Comment by jmcdo29** [comment]
Unfortunately, that is probably the best path forward. It's definitely a limitation of the framework rather than the module

**Comment by jmcdo29** [comment]
As this seems to more of a limitation of the framework than the module itself, would you be okay with closing this issue?
